// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Untitledaaaaaaaaaaaaaa', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Untitledaaaaaaaaaaaaaa', async function() {
    await driver.get("https://app.actuar.com/#/clientes/perfil-cliente/dafb49dc-6300-4e12-ad46-064435aea444")
    await driver.manage().window().setRect({ width: 974, height: 1008 })
    await driver.findElement(By.css(".mt-10:nth-child(3) > .col-xs-12")).click()
    await driver.findElement(By.css(".busca > .ng-tns-c359-1")).click()
    await driver.findElement(By.name("termoBusca")).sendKeys("YF7414")
    await driver.findElement(By.css(".result-item img")).click()
    await driver.findElement(By.css("#comentaros-perfil .titulo")).click()
    await driver.findElement(By.css(".mb-20")).click()
    {
      const element = await driver.findElement(By.css(".mb-20"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".form-group:nth-child(2) > .form-control")).click()
    await driver.findElement(By.css(".form-group:nth-child(2) > .form-control")).click()
    await driver.findElement(By.css(".ng-touched:nth-child(2)")).click()
    await driver.findElement(By.css(".ng-invalid > .modal-footer")).click()
    await driver.findElement(By.css(".ng-touched:nth-child(2)")).click()
    await driver.findElement(By.css(".ng-touched:nth-child(2)")).sendKeys("Último Login:\\n\\nValor Aberto: R$0,00\\n\\nPague.lá: Não tem.\\n\\nObs: Cliente em dias e logando normalmente.\\n\\nMensagem Ativa Enviada \\n\\nTicket#:\\n\\n")
    await driver.findElement(By.css(".ng-invalid > .modal-footer")).click()
    await driver.findElement(By.css(".col-12 > .form-group > .ng-untouched")).click()
    {
      const element = await driver.findElement(By.css(".col-12 > .form-group:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    await driver.findElement(By.css(".modal-body > .col-12")).click()
    await driver.findElement(By.css(".has-danger > .form-control")).click()
    await driver.findElement(By.css(".form-group:nth-child(1) > .ng-touched")).sendKeys("Sprint 30")
    await driver.findElement(By.css(".ng-touched > .modal-footer")).click()
    await driver.findElement(By.css(".ng-touched > .modal-footer")).click()
    await driver.findElement(By.css(".modal-footer > .btn-salvar:nth-child(2) > .ladda-label")).click()
    {
      const element = await driver.findElement(By.css(".modal-footer > .btn-salvar:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
